Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Agenda.Data;
using Agenda.Interfaces;
using Agenda.Models.ScheduleModels;
using Agenda.Models.WorkCenterModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Agenda.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly IMapper _mapper;
        private readonly AppDbContext _context;
        private readonly ICookieService _cookieService;
        private readonly User user;

        public ScheduleController(IMapper mapper,AppDbContext context , ICookieService cookieService)
        {
            _mapper = mapper;
            _context = context;
            _cookieService = cookieService;
            user = _cookieService.GetUser();
        }

        public async Task<IActionResult> Index()
        {
            var schedules = _context.Workcenters.Where(w => w.Userid == user.Userid ).SelectMany(w => w.Schedules);
                    return schedules != null ? 
                        View(await schedules.OrderBy(s => s.Workdate).ToListAsync()) :
                        Problem("Entity set 'SiscomContext.RangoFirmas'  is null.");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("Workdate,Starttime,Endtime,Workedhours,Description")] ScheduleCreate schedule)
        {
            if (ModelState.IsValid){
                schedule.Centerid = id;
                await _context.AddAsync(_mapper.Map<Schedule>(schedule));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            return View(schedule);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }
            
            return View(_mapper.Map<ScheduleCreate>(schedule));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Workdate,Starttime,Endtime,Workedhours,Description")] ScheduleCreate scheduleCreate)
        {
            var schedule = await _context.Schedules.FirstOrDefaultAsync(w => w.Scheduleid == id);
            if (schedule == null)
            {
                return NotFound();
            }

            schedule.Workdate = scheduleCreate.Workdate;
            schedule.Starttime = scheduleCreate.Starttime;
            schedule.Endtime = scheduleCreate.Endtime;
            schedule.Workedhours = scheduleCreate.Workedhours;
            schedule.Description = scheduleCreate.Description;

            if (ModelState.IsValid)
            {
                _context.Schedules.Update(schedule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schedule);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule != null)
            {
                _context.Schedules.Remove(schedule);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/WorkCenterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Agenda.Data;
using Agenda.Interfaces;
using Agenda.Models.WorkCenterModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Agenda.Controllers
{
    public class WorkCenterController : Controller
    {
        private readonly IMapper _mapper;
        private readonly AppDbContext _context;
        private readonly ICookieService _cookieService;
        private readonly User user;

        public WorkCenterController(IMapper mapper,AppDbContext context , ICookieService cookieService)
        {
            _mapper = mapper;
            _context = context;
            _cookieService = cookieService;
            user = _cookieService.GetUser();
        }

        public async Task<IActionResult> Index()
        {
            var workcenters = _context.Workcenters.Where(w => w.Userid == user.Userid);
            return workcenters != null ? 
                        View(await workcenters.ToListAsync()) :
                        Problem("Entity set 'SiscomContext.RangoFirmas'  is null.");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,Grossrate,Paymentday,Netrate")] WorkCenterCreate workCenter)
        {
            if (ModelState.IsValid){
                workCenter.Userid = user.Userid;
                await _context.AddAsync(_mapper.Map<Workcenter>(workCenter));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            return View(workCenter);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Workcenters == null)
            {
                return NotFound();
            }

            var workcenter = await _context.Workcenters.FindAsync(id);
            if (workcenter == null)
            {
                return NotFound();
            }
            
            return View(_mapper.Map<WorkCenterCreate>(workcenter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Address,Grossrate,Paymentday,Netrate,IsActive")] WorkCenterCreate workCenter)
        {
            var center = await _context.Workcenters.FirstOrDefaultAsync(w => w.Centerid == id);
            if (center == null)
            {
                return NotFound();
            }

            center.Name = workCenter.Name;
            center.Address = workCenter.Address;
            center.Grossrate = workCenter.Grossrate;
            center.Paymentday = workCenter.Paymentday;
            center.Netrate = workCenter.Netrate;
            center.IsActive = workCenter.IsActive;

            if (ModelState.IsValid)
            {
                _context.Workcenters.Update(center);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(center);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var workcenter = await _context.Workcenters.FindAsync(id);
            if (workcenter != null)
            {
                _context.Workcenters.Remove(workcenter);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/WorkCenter/Create.cshtml
@model Agenda.Models.WorkCenterModels.WorkCenterCreate

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" method="post">
  <div class="space-y-12 p-4 md:px-16">
    <div class="border-b border-gray-900/10 pb-12">
      <h2 class="text-base font-semibold leading-7 text-gray-900">Añadir Centro</h2>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label asp-for="Name" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
          <div class="mt-2">
            <input asp-for="Name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Address" class="block text-sm font-medium leading-6 text-gray-900">Dirección</label>
          <div class="mt-2">
            <input asp-for="Address" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Grossrate" class="block text-sm font-medium leading-6 text-gray-900">Bruto</label>
          <div class="mt-2">
            <input asp-for="Grossrate" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Grossrate" class="text-red-500"></span>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Paymentday" class="block text-sm font-medium leading-6 text-gray-900">Cobro</label>
          <div class="mt-2">
            <input type="number" asp-for="Paymentday" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Paymentday" class="text-red-500"></span>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Netrate" class="block text-sm font-medium leading-6 text-gray-900">Neto</label>
          <div class="mt-2">
            <input asp-for="Netrate" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Netrate" class="text-red-500"></span>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6 px-4 md:px-16">
    <button asp-action="Index" class="text-sm font-semibold leading-6 text-gray-900">Cancelar</button>
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Crear</button>
  </div>
</form>


Views/WorkCenter/Edit.cshtml
@model Agenda.Models.WorkCenterModels.WorkCenterCreate

@{
    ViewData["Title"] = "Edit";
}

<form asp-action="Edit" method="post">
    @Html.AntiForgeryToken()
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <div class="space-y-12 p-4 md:px-16">
    <div class="border-b border-gray-900/10 pb-12">
      <h2 class="text-base font-semibold leading-7 text-gray-900">Editar Centro</h2>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label asp-for="Name" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
          <div class="mt-2">
            <input asp-for="Name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Address" class="block text-sm font-medium leading-6 text-gray-900">Dirección</label>
          <div class="mt-2">
            <input asp-for="Address" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Grossrate" class="block text-sm font-medium leading-6 text-gray-900">Bruto</label>
          <div class="mt-2">
            <input asp-for="Grossrate" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Grossrate" class="text-red-500"></span>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Paymentday" class="block text-sm font-medium leading-6 text-gray-900">Cobro</label>
          <div class="mt-2">
            <input type="number" asp-for="Paymentday" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Paymentday" class="text-red-500"></span>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Netrate" class="block text-sm font-medium leading-6 text-gray-900">Neto</label>
          <div class="mt-2">
            <input asp-for="Netrate" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            <span asp-validation-for="Netrate" class="text-red-500"></span>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label asp-for="Netrate" class="block text-sm font-medium leading-6 text-gray-900">En activo</label>
          <div class="mt-2">
            <input asp-for="IsActive" type="checkbox">
            <span asp-validation-for="IsActive" class="text-red-500"></span>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6 px-4 md:px-16">
    <button asp-action="Index" class="text-sm font-semibold leading-6 text-gray-900">Cancelar</button>
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar</button>
  </div>
</form>

@* <h1>Edit</h1>

<h4>RangoFirma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grossrate" class="control-label"></label>
                <input asp-for="Grossrate" class="form-control" />
                <span asp-validation-for="Grossrate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Netrate" class="control-label"></label>
                <input asp-for="Netrate" class="form-control" />
                <span asp-validation-for="Netrate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn" asp-action="Index">Back to List</a>
</div> *@


Views/WorkCenter/Index.cshtml
@model IEnumerable<Agenda.Data.Workcenter>

@{
    ViewData["Title"] = "Index";
}

<div class="px-4 mt-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Centro de Trabajo</h1>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <a asp-action="Create" asp-controller="WorkCenter" type="button" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Añadir centro de trabajo</a>
    </div>
  </div>
  <div class="-mx-4 mt-8 sm:-mx-0">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">@Html.DisplayNameFor(model => model.Name)</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">@Html.DisplayNameFor(model => model.Address)</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">@Html.DisplayNameFor(model => model.IsActive)</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">@Html.DisplayNameFor(model => model.Grossrate)</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">@Html.DisplayNameFor(model => model.Paymentday)</th>
          <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">@Html.DisplayNameFor(model => model.Netrate)</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
            <span class="sr-only">Editar</span>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        @foreach (var item in Model) {
        <tr>
          <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-0">
            @Html.DisplayFor(modelItem => item.Name)
            <dl class="font-normal lg:hidden">
              <dd class="mt-1 truncate text-gray-700">@Html.DisplayFor(modelItem => item.Address)</dd>
              <dd class="mt-1 truncate text-gray-700">@Html.DisplayFor(modelItem => item.Grossrate)</dd>
              <dd class="mt-1 truncate text-gray-700">@Html.DisplayFor(modelItem => item.Paymentday)</dd>
              <dt class="sr-only sm:hidden">@Html.DisplayFor(modelItem => item.Netrate)</dt>
            </dl>
          </td>
          <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">@Html.DisplayFor(modelItem => item.Address)</td>
          <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">@Html.DisplayFor(modelItem => item.IsActive)</td>
          <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell">@Html.DisplayFor(modelItem => item.Grossrate)</td>
          <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell">@Html.DisplayFor(modelItem => item.Paymentday)</td>
          <td class="px-3 py-4 text-sm text-gray-500">@Html.DisplayFor(modelItem => item.Netrate)</td>
          <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
            <a asp-action="Edit" asp-controller="WorkCenter" asp-route-id="@item.Centerid" class="text-amber-700 hover:text-amber-900">Editar</a> |
            <form asp-action="Delete" method="post" asp-route-id="@item.Centerid" onsubmit="return confirm('Are you sure you want to delete this WorkCenter')">
                    @Html.AntiForgeryToken()
                    <button type="submit" class="text-red-700 hover:text-red-900">Eliminar</button> |
            </form>
            <a asp-action="Create" asp-controller="Schedule" asp-route-id="@item.Centerid" class="text-green-700 hover:text-green-900">Añadir horario</a>
          </td>
        </tr>
    }
      </tbody>
      @if (ViewData.ModelState.IsValid == false)
                {
                    <div class="mb-4 mt-2">
                        <p class="text-red-500 text-sm">@Html.ValidationSummary(false, "", new { @class = "text-sm text-red-500" })</p>
                    </div>
                }
    </table>
  </div>
</div>