Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Agenda.Data;
using Agenda.Interfaces;
using Agenda.Models.UserModels;
using AutoMapper;
using DotNetEnv;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;


namespace Agenda.Controllers
{
    public class SessionController : Controller
    {
        private readonly ILogger<SessionController> _logger;
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;

        public SessionController(ILogger<SessionController> logger, AppDbContext context, IMapper mapper)
        {
            _logger = logger;
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLogin user)
        {
            try
            {
                //Buscando el usuario
                var login = await _context.Users.FirstOrDefaultAsync(u => u.Email == user.Email && u.Password == user.Password);
                
                if (login == null)
                {
                    ModelState.AddModelError(string.Empty, "El nombre de usuario o la contraseña son incorrectos.");
                    return View("Index");
                }
                
                //Guardando el token en las cookies
                List<Claim> claims = new List<Claim> () {
                new Claim("user", JsonSerializer.Serialize(login))
                };

                ClaimsIdentity ci = new ClaimsIdentity (claims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal cp = new ClaimsPrincipal (ci);
                await HttpContext.SignInAsync(cp, new AuthenticationProperties{IsPersistent=true});
                
                return RedirectToAction("Index", "Dashboard");
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        public async Task<IActionResult> Logout(){
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }

        public IActionResult Register(){
            return View();
        }
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(UserRegister user){
            try
            {
                var email = await _context.Users.FirstOrDefaultAsync(u => u.Email == user.Email);
                if (email != null) {
                    ModelState.AddModelError(string.Empty, "Ya existe un usuario con ese correo.");
                    return View("Register");
                }
                var newuser = _mapper.Map<User>(user);
                await _context.Users.AddAsync(newuser);
                await _context.SaveChangesAsync();
                return View("Index");
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);;
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Session/Index.cshtml
@{
  ViewData["Title"] = "Index";
  Layout = "~/Views/Shared/_LayoutSession.cshtml";
}
<div class="flex justify-center items-center h-screen w-screen bg-red">
  <div class="mt-10 drop-shadow-[10px_22px_12px_rgba(0,0,0,0.25)] h-full w-full sm:h-auto sm:mx-auto sm:w-full sm:max-w-[480px]">
    <div class="bg-white h-full px-6 py-8 shadow sm:rounded-lg sm:px-12">
      <div class="flex flex-col justify-center pb-6 sm:px-6 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-md">
          <img class="mx-auto h-10 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
            alt="Your Company">
        </div>
      </div>
      <form class="space-y-6" asp-action="Login" asp-controller="Session">
        @Html.AntiForgeryToken()
        <div>
          <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email</label>
          <div class="mt-2">
            <input id="email" name="email" type="email" autocomplete="email" required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div>
          <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Contraseña</label>
          <div class="mt-2">
            <input id="password" name="password" type="password" autocomplete="current-password" required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
          </div>

          <div class="text-sm leading-6">
            <a asp-action="Register" asp-controller="Session" class="font-semibold text-indigo-600 hover:text-indigo-500">No tienes una cuenta?</a>
          </div>
        </div>

        <div>
          <button type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Iniciar cesión</button>
        </div>
      </form>
      @if (ViewData.ModelState.IsValid == false)
                {
                    <div class="mb-4 mt-2">
                        <p class="text-red-500 text-sm">@Html.ValidationSummary(false, "", new { @class = "text-sm text-red-500" })</p>
                    </div>
                }
      
      <div>
        <div class="relative mt-10">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-200"></div>
          </div>
          <div class="relative flex justify-center text-sm font-medium leading-6">
            <span class="bg-white px-6 text-gray-900">Continuar con</span>
          </div>
        </div>

        <div class="mt-6 gap-4">
          <a href="#"
            class="flex w-full items-center justify-center gap-3 border-2 border-indigo-600 hover:bg-indigo-100 rounded-md px-3 py-1.5 text-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1D9BF0]">
            <svg class="h-7 w-7" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path
                d="M15.706 8.16699C15.706 7.64699 15.6593 7.14699 15.5727 6.66699H8.66602V9.50699H12.6127C12.4393 10.4203 11.9193 11.1937 11.1393 11.7137V13.5603H13.5193C14.906 12.2803 15.706 10.4003 15.706 8.16699Z"
                fill="#4285F4"></path>
              <path
                d="M8.66581 15.3337C10.6458 15.3337 12.3058 14.6804 13.5191 13.5604L11.1391 11.7137C10.4858 12.1537 9.65247 12.4204 8.66581 12.4204C6.75914 12.4204 5.13914 11.1337 4.55914 9.40039H2.11914V11.2937C3.32581 13.6871 5.79914 15.3337 8.66581 15.3337Z"
                fill="#34A853"></path>
              <path
                d="M4.55967 9.39289C4.41301 8.95289 4.32634 8.48622 4.32634 7.99956C4.32634 7.51289 4.41301 7.04622 4.55967 6.60622V4.71289H2.11967C1.61967 5.69956 1.33301 6.81289 1.33301 7.99956C1.33301 9.18622 1.61967 10.2996 2.11967 11.2862L4.01967 9.80622L4.55967 9.39289Z"
                fill="#FBBC05"></path>
              <path
                d="M8.66581 3.58699C9.74581 3.58699 10.7058 3.96033 11.4725 4.68033L13.5725 2.58033C12.2991 1.39366 10.6458 0.666992 8.66581 0.666992C5.79914 0.666992 3.32581 2.31366 2.11914 4.71366L4.55914 6.60699C5.13914 4.87366 6.75914 3.58699 8.66581 3.58699Z"
                fill="#EA4335"></path>
            </svg>
            <span class="text-sm font-bold leading-6">Gmail</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

Views/Session/Register.cshtml
@model Agenda.Models.UserModels.UserRegister
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_LayoutSession.cshtml";
}

<div class="flex justify-center items-center h-screen w-screen bg-red">
  <div class="mt-10 drop-shadow-[10px_22px_12px_rgba(0,0,0,0.25)] h-full w-full sm:h-auto sm:mx-auto sm:w-full sm:max-w-[480px]">
    <div class="bg-white h-full px-6 py-8 shadow sm:rounded-lg sm:px-12">
      <div class="flex flex-col justify-center pb-6 sm:px-6 lg:px-8">
        <div class="text-2xl font-bold sm:mx-auto sm:w-full sm:max-w-md text-center ">
          Registrar Usuario
        </div>
      </div>
      <form class="space-y-6" asp-action="RegisterUser" asp-controller="Session">
        @Html.AntiForgeryToken()
        <div>
          <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
          <div class="mt-2">
            <input id="name" name="name" type="text" autocomplete="off" required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>
        <div>
          <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email</label>
          <div class="mt-2">
            <input id="email" name="email" type="email" autocomplete="off" required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div>
          <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Contraseña</label>
          <div class="mt-2">
            <input id="password" name="password" type="password" autocomplete="off" required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
          </div>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
          </div>

          <div class="text-sm leading-6">
            <a asp-action="Index" asp-controller="Session" class="font-semibold text-indigo-600 hover:text-indigo-500">Tienes una cuenta?</a>
          </div>
        </div>

        <div>
          <button type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Registrar</button>
        </div>
      </form>
      @if (ViewData.ModelState.IsValid == false)
        {
            <div class="mb-4 mt-2 text-center">
                <p class="text-red-500 text-sm">@Html.ValidationSummary(false, "", new { @class = "text-sm text-red-500" })</p>
            </div>
        }
    </div>
  </div>
</div>