Models/CalendarModels/Calendar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Agenda.Data;

namespace Agenda.Models.CalendarModels
{
    public class Calendar
    {
        public DateOnly Date {get; set;}
        public User User {get; set;}
    }
}

Controllers/CalendarController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Agenda.Models;
using Agenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Agenda.Services;
using Agenda.Models.CalendarModels;
using System.Text.Json;
using System.Security.Claims;
using Agenda.Interfaces;

namespace Agenda.Controllers;

[Authorize]
[TypeFilter(typeof(ValidateUserFilter))]
public class CalendarController : Controller
{
    private readonly ICookieService _cookieService;
    private readonly AppDbContext _context;
    private readonly User user;
    public CalendarController(ICookieService cookieService, AppDbContext context)
    {
        _cookieService = cookieService;
        _context = context;
        user = _cookieService.GetUser();
    }

    public IActionResult Index()
    {
        var userRet = _context.Users.FirstOrDefault(s => s.Userid == user.Userid);
        var calendar =new Calendar{ 
            Date = DateOnly.FromDateTime(DateTime.Now), 
            User = userRet
            }; 
        return View(calendar);
    }

    public IActionResult UpdateCalendar(DateSubmit dateSubmit) {
        var userRet = _context.Users.FirstOrDefault(s => s.Userid == user.Userid);
        var calendar = new Calendar{ 
            Date = new DateOnly(dateSubmit.Years, dateSubmit.Months, 1),
            User = userRet
            };
        return PartialView("_CalendarPartial", calendar);
    }

    public IActionResult GetScheduleByDate(int day, int month, int year) {
        var date = new DateOnly(year,month,day);
        var schedule = _context.Users.Find(user.Userid).Workcenters.SelectMany(w => w.Schedules).FirstOrDefault(s => s.Workdate == date);
        return PartialView("_ScheduleCardPartial", schedule);
    }
}

Controllers/WorkCenterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Agenda.Data;
using Agenda.Interfaces;
using Agenda.Models.WorkCenterModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Agenda.Controllers
{
    public class WorkCenterController : Controller
    {
        private readonly IMapper _mapper;
        private readonly AppDbContext _context;
        private readonly ICookieService _cookieService;
        private readonly User user;

        public WorkCenterController(IMapper mapper,AppDbContext context , ICookieService cookieService)
        {
            _mapper = mapper;
            _context = context;
            _cookieService = cookieService;
            user = _cookieService.GetUser();
        }

        public async Task<IActionResult> Index()
        {
            var workcenters = _context.Workcenters.Where(w => w.Userid == user.Userid);
            return workcenters != null ? 
                        View(await workcenters.ToListAsync()) :
                        Problem("Entity set 'SiscomContext.RangoFirmas'  is null.");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,Grossrate,Paymentday,Netrate")] WorkCenterCreate workCenter)
        {
            if (ModelState.IsValid){
                workCenter.Userid = user.Userid;
                await _context.AddAsync(_mapper.Map<Workcenter>(workCenter));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            return View(workCenter);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Workcenters == null)
            {
                return NotFound();
            }

            var workcenter = await _context.Workcenters.FindAsync(id);
            if (workcenter == null)
            {
                return NotFound();
            }
            
            return View(_mapper.Map<WorkCenterCreate>(workcenter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Address,Grossrate,Paymentday,Netrate,IsActive")] WorkCenterCreate workCenter)
        {
            var center = await _context.Workcenters.FirstOrDefaultAsync(w => w.Centerid == id);
            if (center == null)
            {
                return NotFound();
            }

            center.Name = workCenter.Name;
            center.Address = workCenter.Address;
            center.Grossrate = workCenter.Grossrate;
            center.Paymentday = workCenter.Paymentday;
            center.Netrate = workCenter.Netrate;
            center.IsActive = workCenter.IsActive;

            if (ModelState.IsValid)
            {
                _context.Workcenters.Update(center);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(center);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var workcenter = await _context.Workcenters.FindAsync(id);
            if (workcenter != null)
            {
                _context.Workcenters.Remove(workcenter);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Calendar/Index.cshtml
@model Agenda.Models.CalendarModels.Calendar
@{
  ViewData["Title"] = "Calendar Page";
}

<div class="p-12">
  <div class="lg:flex lg:h-full lg:flex-col">
    <header class="flex items-center justify-between border-b border-gray-200 sm:px-6 py-4 lg:flex-none">
      <h1 class="text-base font-semibold leading-6 text-gray-900">
        <time class="text-2xl" datetime="@Model.Date.ToString("yyyy-MM-dd")">@Model.Date.ToString("MMMM")</time>
      </h1>
      <div class="flex items-center">
        <form class="flex items-center" id="calendarForm" asp-action="UpdateCalendar" asp-controller="Calendar">
          <div class="w-full max-w-xs">
            <select id="months" name="months"
              class="block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
              <option class="md:hidden" value="1">Ene</option>
              <option class="hidden sm:block" value="1">Enero</option>
              <option class="md:hidden" value="2">Feb</option>
              <option class="hidden sm:block" value="2">Febrero</option>
              <option class="md:hidden" value="3">Mar</option>
              <option class="hidden sm:block" value="3">Marzo</option>
              <option class="md:hidden" value="4">Abr</option>
              <option class="hidden sm:block" value="4">Abril</option>
              <option class="md:hidden" value="5">May</option>
              <option class="hidden sm:block" value="5">Mayo</option>
              <option class="md:hidden" value="6">Jun</option>
              <option class="hidden sm:block" value="6">Junio</option>
              <option class="md:hidden" value="7">Jul</option>
              <option class="hidden sm:block" value="7">Julio</option>
              <option class="md:hidden" value="8">Ago</option>
              <option class="hidden sm:block" value="8">Agosto</option>
              <option class="md:hidden" value="9">Sep</option>
              <option class="hidden sm:block" value="9">Septiembre</option>
              <option class="md:hidden" value="10">Oct</option>
              <option class="hidden sm:block" value="10">Octubre</option>
              <option class="md:hidden" value="11">Nov</option>
              <option class="hidden sm:block" value="11">Noviembre</option>
              <option class="md:hidden" value="12">Dic</option>
              <option class="hidden sm:block" value="12">Diciembre</option>
            </select>
          </div>
          <div class="w-full max-w-xs mx-2">
            <select id="years" name="years"
              class="block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
              <option value="2024">2024</option>
              <option value="2025">2025</option>
              <option value="2026">2026</option>
              <option value="2027">2027</option>
              <option value="2028">2028</option>
              <option value="2029">2029</option>
              <option value="2030">2030</option>
            </select>
          </div>
          <div class="flex items-center">
            <button type="submit"
              class=" rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd"
                  d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
                  clip-rule="evenodd" />
              </svg>
            </button>
          </div>
        </form>
        <div class="hidden md:ml-4 md:flex md:items-center">
          <div class="ml-6 h-6 w-px bg-gray-300"></div>
          <a asp-action="Index" asp-controller="WorkCenter"
            class="ml-6 rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Añadir
            Horario</a>
        </div>
        <div class="hidden relative ml-6 md:hidden">
          <button type="button"
            class="-mx-2 flex items-center rounded-full border border-transparent p-2 text-gray-400 hover:text-gray-500"
            id="menu-0-button" aria-expanded="false" aria-haspopup="true">
            <span class="sr-only">Open menu</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path
                d="M3 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM8.5 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM15.5 8.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
            </svg>
          </button>
        </div>
      </div>
    </header>
    <div id="calendarContent" class="mt-6">
      @Html.Partial("_CalendarPartial", Model)
    </div>
  </div>
</div>
@section Scripts {
  <script>
    $(document).ready(function () {
      $('#calendarForm').submit(function (event) {
        event.preventDefault();

        var month = $('#months').val();
        var year = $('#years').val();

        $.ajax({
          url: '@Url.Action("UpdateCalendar", "Calendar")',
          data: {
            months: month,
            years: year
          },
          success: function (result) {
            $('#calendarContent').html(result);
          },
          error: function () {
            alert('Error al actualizar el calendario');
          }
        });
      });
    });
  </script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var currentDate = new Date();
      var currentMonth = currentDate.getMonth() + 1;
      var currentYear = currentDate.getFullYear();

      document.getElementById("months").value = currentMonth;
      document.getElementById("years").value = currentYear;
    });
  </script>
}

Views/Calendar/_CalendarPartial.cshtml
@model Agenda.Models.CalendarModels.Calendar
@{
  var date = Model.Date;
  var schedules = Model.User.Workcenters.SelectMany(w => w.Schedules);

  var firstday = new DateOnly(date.Year, date.Month, 1);
  var weekday = firstday.DayOfWeek;
  var daysinmonth = DateTime.DaysInMonth(date.Year, date.Month);
  var startday = ((int)DayOfWeek.Saturday - (int)firstday.DayOfWeek) - 6;
}
<div class="shadow ring-1 ring-black ring-opacity-5 lg:flex lg:flex-auto lg:flex-col">
  <div
    class="grid grid-cols-7 gap-px border-b border-gray-300 bg-gray-200 text-center text-xs font-semibold leading-6 text-gray-700 lg:flex-none">
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">D</span>
      <span class="sr-only sm:not-sr-only">Domingo</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">L</span>
      <span class="sr-only sm:not-sr-only">Lunes</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">M</span>
      <span class="sr-only sm:not-sr-only">Martes</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">X</span>
      <span class="sr-only sm:not-sr-only">Miércoles</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">J</span>
      <span class="sr-only sm:not-sr-only">Jueves</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">V</span>
      <span class="sr-only sm:not-sr-only">Viernes</span>
    </div>
    <div class="flex justify-center bg-white py-2">
      <span class="md:hidden">S</span>
      <span class="sr-only sm:not-sr-only">Sábado</span>
    </div>
  </div>
  <div class="flex bg-gray-100 text-xs leading-6 text-gray-700 lg:flex-auto">
    <div class="hidden w-full lg:grid lg:grid-cols-7 lg:gap-px">
      @for (int i = startday; i < daysinmonth; i++)
      {
        if (i < 0)
        {
          <div class="relative bg-gray-100 px-3 py-2">
          </div>
        }
        else
        {
          var datenow = firstday.AddDays(i);
          var schedule = schedules.Where(f => f.Workdate == datenow);

          @if (schedule.Count() > 0)
          {
            <div class="relative bg-yellow-100 px-3 py-2 hover:cursor-pointer">
              <time datetime="@datenow">@datenow.ToString("dd")</time>
              <ol>
                @foreach (var item in schedule)
                {
                  <li>
                    <span
                      class="flex-auto truncate font-medium text-gray-900 group-hover:text-indigo-600">@item.Center.Name</span>
                    <div class="group flex">
                      <time datetime="@item.Starttime"
                        class="ml-3 hidden flex-none text-gray-500 group-hover:text-indigo-600 xl:block">@item.Starttime</time>
                      <time datetime="@item.Endtime"
                        class="ml-3 hidden flex-none text-gray-500 group-hover:text-indigo-600 xl:block">@item.Endtime</time>
                    </div>
                  </li>
                }
              </ol>
            </div>
          }
          else
          {
            <div class="relative bg-white px-3 py-2">
              <time datetime="@datenow">@datenow.ToString("dd")</time>
            </div>
          }
        }

      }
    </div>

    <!--
            Always include: "relative py-2 px-3"
            Is current month, include: "bg-white"
            Is not current month, include: "bg-gray-50 text-gray-500"
          -->
    <div class="isolate grid w-full grid-cols-7 gap-px lg:hidden">
      <!--
            Always include: "flex h-14 flex-col py-2 px-3 hover:bg-gray-100 focus:z-10"
            Is current month, include: "bg-white"
            Is not current month, include: "bg-gray-50"
            Is selected or is today, include: "font-semibold"
            Is selected, include: "text-white"
            Is not selected and is today, include: "text-indigo-600"
            Is not selected and is current month, and is not today, include: "text-gray-900"
            Is not selected, is not current month, and is not today: "text-gray-500"
          -->
      @for (int i = startday; i < daysinmonth; i++)
      {
        if (i < 0)
        {
          <div class="relative bg-gray-100 px-3 py-2">
          </div>
        }
        else
        {
          var datenow = firstday.AddDays(i);
          var schedule = schedules.Where(f => f.Workdate == datenow);

          @if (schedule.Count() > 0)
          {
            <div class="relative bg-yellow-100 px-3 py-2 hover:cursor-pointer" onclick="loadSchedule(@datenow.Day, @datenow.Month, @datenow.Year)">
              <time datetime="@datenow">@datenow.ToString("dd")</time>
            </div>
          }
          else
          {
            <div class="relative bg-white px-3 py-2" onclick="loadSchedule(@datenow.Day, @datenow.Month, @datenow.Year)">
              <time datetime="@datenow">@datenow.ToString("dd")</time>
            </div>
          }
        }
      }
    </div>
  </div>
</div>
<div id="schedule-card-container" class="mt-6">
</div>

<script>
  function loadSchedule(day, month, year) {
    $.ajax({
      url: '@Url.Action("GetScheduleByDate", "Calendar")',
      type: 'GET',
      data: { day: day,
              month: month,
              year: year },
      success: function (result) {
        $('#schedule-card-container').html(result);
      },
      error: function (xhr, status, error) {
        console.error(error);
      }
    });
  }
</script>

Views/Calendar/_ScheduleCardPartial.cshtml
@model Agenda.Data.Schedule

@{
  if (Model == null)
  {
    <div>
      Día libre
    </div>
  }
  else
  {
    <div class="md:hidden divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow mt-10">
      <div class="px-4 py-5 sm:px-6 text-center">
        <!-- Content goes here -->
        <span id="">@Model.Center.Name -</span>
        <span class="">@Model.Workedhours</span>
        <!-- We use less vertical padding on card headers on desktop than on body sections -->
      </div>
      <div class="px-4 py-5 sm:p-6">
        <div>
          <time datetime="09:00" class="ml-3  flex-none text-gray-500 group-hover:text-indigo-600 xl:block">Horario: @Model.Starttime
            </time>
          <time datetime="18:00" class="ml-3  flex-none text-gray-500 group-hover:text-indigo-600 xl:block">@Model.Endtime</time>
        </div>
        <div>
          <span class="ml-3  flex-none text-gray-500 group-hover:text-indigo-600 xl:block">Descripción: @Model.Description</span>
        </div>
      </div>
    </div>
  }
}